#ifndef APP_SIGNALS_H
#define APP_SIGNALS_H

typedef enum
{
    APP_SIGNAL_NONE = 0,
    APP_SIGNAL_SYSTEM_START,
    APP_SIGNAL_BUTTON_EDGE,
    APP_SIGNAL_BUTTON_DEBOUNCE_TIMEOUT,
    APP_SIGNAL_BUTTON_PRESSED,
    APP_SIGNAL_LED_ON,
    APP_SIGNAL_LED_OFF,
    APP_SIGNAL_LED_TOGGLE,
    APP_SIGNAL_LED_BLINK_START,
    APP_SIGNAL_LED_BLINK_STOP,
    APP_SIGNAL_LED_BLINK_TICK,
    APP_SIGNAL_UART_RX_BYTE,
    APP_SIGNAL_APP_ERROR,
    APP_SIGNAL_APP_RESET,
    APP_SIGNAL_SENSOR_SAMPLE,
    APP_SIGNAL_SENSOR_DATA,
    APP_SIGNAL_SHELL_COMMAND
} app_signal_t;

#endif
