#ifndef EVENT_H
#define EVENT_H

#include <stdint.h>

typedef enum
{
    EVENT_SOURCE_SYSTEM = 0,
    EVENT_SOURCE_ISR,
    EVENT_SOURCE_TIMER,
    EVENT_SOURCE_BUTTON,
    EVENT_SOURCE_APP,
    EVENT_SOURCE_LED,
    EVENT_SOURCE_UART,
    EVENT_SOURCE_TEST
} event_source_t;

typedef enum
{
    EVENT_DESTINATION_NONE = 0,
    EVENT_DESTINATION_APP,
    EVENT_DESTINATION_BUTTON,
    EVENT_DESTINATION_LED,
    EVENT_DESTINATION_UART,
    EVENT_DESTINATION_COUNT
} event_destination_t;

typedef enum
{
    SIGNAL_NONE = 0,

    SIGNAL_SYSTEM_START,
    SIGNAL_SENSOR_READY,
    SIGNAL_ERROR_DETECTED,
    SIGNAL_RESET_REQUEST,

    SIGNAL_BUTTON_EDGE,
    SIGNAL_BUTTON_DEBOUNCE_TIMEOUT,
    SIGNAL_BUTTON_PRESSED,
    SIGNAL_BUTTON_RELEASED,

    SIGNAL_LED_ON,
    SIGNAL_LED_OFF,
    SIGNAL_LED_BLINK_START,
    SIGNAL_LED_BLINK_STOP,
    SIGNAL_LED_TIMEOUT,

    SIGNAL_UART_RX_BYTE,
    SIGNAL_UART_STATUS_REQUEST,
    SIGNAL_UART_STATUS_BOOT,
    SIGNAL_UART_STATUS_IDLE,
    SIGNAL_UART_STATUS_ACTIVE,
    SIGNAL_UART_STATUS_ERROR
} signal_t;

typedef struct
{
    uint32_t timestamp_ms;
    uint32_t parameter;
    uint16_t signal;
    uint8_t source;
    uint8_t destination;
} event_t;

#endif
